import Mathlib
import StochasticQuantization.HistoryFilter
import StochasticQuantization.SlowFast
import StochasticQuantization.StationaryMixture

noncomputable section

/-!
# Fast switching as temporal averaging

The same fading-memory map used to describe finite Ras memory also gives an exact
minimal model of the Model-3 regime.  Alternate two target levels with the same
retention `a`.  The periodic fixed point lies between the two codewords; as
`a -> 1` (very short dwells compared with target relaxation) it approaches their
arithmetic mean.  At `a = 0` the readout tracks the newest state exactly.
-/

namespace StochasticQuantization
namespace Theory
namespace FastSwitching

open HistoryFilter


/-- Product of retention factors across a finite repeated switching history. -/
def historyGain (hs : List (ℝ × ℝ)) : ℝ := (hs.map Prod.fst).prod

/-- State-independent affine offset accumulated from all codewords in a history. -/
def historyOffset (hs : List (ℝ × ℝ)) : ℝ := run hs 0

/-- Every finite fading-memory history is one affine map: previous state times the
retention product plus a history-dependent offset.  This is derived from the
existing `HistoryFilter.run_sub` theorem rather than re-expanding the recurrence. -/
theorem run_eq_gain_mul_add (hs : List (ℝ × ℝ)) (x : ℝ) :
    run hs x = historyGain hs * x + historyOffset hs := by
  have h := run_sub hs x 0
  unfold historyGain historyOffset at *
  ring_nf at h ⊢
  linarith

/-- Periodic fixed point of an arbitrary finite switching history whenever one
full cycle retains a fraction different from one. -/
def periodicFixed (hs : List (ℝ × ℝ)) : ℝ :=
  historyOffset hs / (1 - historyGain hs)

/-- The generic closed form is genuinely fixed by repeating the history. -/
theorem periodicFixed_is_fixed
    (hs : List (ℝ × ℝ)) (hcontract : 1 - historyGain hs ≠ 0) :
    run hs (periodicFixed hs) = periodicFixed hs := by
  rw [run_eq_gain_mul_add]
  unfold periodicFixed
  field_simp [hcontract]
  ring

/-- One complete two-state switching cycle. -/
def cycle (a μ₀ μ₁ x : ℝ) : ℝ :=
  run [(a, μ₀), (a, μ₁)] x

/-- Closed-form periodic fixed point for a two-state equal-retention cycle. -/
def cycleFixed (a μ₀ μ₁ : ℝ) : ℝ :=
  (a * μ₀ + μ₁) / (1 + a)

/-- Exact affine form of one switching cycle. -/
theorem cycle_eq (a μ₀ μ₁ x : ℝ) :
    cycle a μ₀ μ₁ x =
      a ^ 2 * x + (1 - a) * (a * μ₀ + μ₁) := by
  simp [cycle, run, step]
  ring

/-- The closed form is genuinely a fixed point whenever `1+a` is nonzero. -/
theorem cycleFixed_is_fixed
    (a μ₀ μ₁ : ℝ) (hden : 1 + a ≠ 0) :
    cycle a μ₀ μ₁ (cycleFixed a μ₀ μ₁) = cycleFixed a μ₀ μ₁ := by
  rw [cycle_eq]
  unfold cycleFixed
  field_simp [hden]
  ring

/-- Exact departure of the periodic readout from the time-average codeword. -/
theorem cycleFixed_sub_average
    (a μ₀ μ₁ : ℝ) (hden : 1 + a ≠ 0) :
    cycleFixed a μ₀ μ₁ - (μ₀ + μ₁) / 2 =
      (1 - a) * (μ₁ - μ₀) / (2 * (1 + a)) := by
  unfold cycleFixed
  field_simp [hden]
  ring

/-- Infinite switching speed in the reduced filter corresponds to retention one,
and the distinguished periodic fixed point is exactly the arithmetic mean. -/
@[simp] theorem cycleFixed_one (μ₀ μ₁ : ℝ) :
    cycleFixed 1 μ₀ μ₁ = (μ₀ + μ₁) / 2 := by
  unfold cycleFixed
  ring

/-- Complete relaxation during each dwell corresponds to retention zero, so the
cycle ends exactly at the most recent target. -/
@[simp] theorem cycleFixed_zero (μ₀ μ₁ : ℝ) :
    cycleFixed 0 μ₀ μ₁ = μ₁ := by
  simp [cycleFixed]

/-- For nonnegative retention, the periodic readout is a convex combination of
the two target codewords and therefore cannot overshoot them. -/
theorem cycleFixed_between
    (a μ₀ μ₁ : ℝ) (ha : 0 ≤ a) (hμ : μ₀ ≤ μ₁) :
    μ₀ ≤ cycleFixed a μ₀ μ₁ ∧ cycleFixed a μ₀ μ₁ ≤ μ₁ := by
  have hden : 0 < 1 + a := by linarith
  constructor
  · unfold cycleFixed
    rw [le_div_iff₀ hden]
    nlinarith
  · unfold cycleFixed
    rw [div_le_iff₀ hden]
    nlinarith

/-- Retention generated by a dwell of duration `dt` at relaxation rate `r`. -/
def dwellRetention (r dt : ℝ) : ℝ := trackingErrorFraction r dt

@[simp] theorem dwellRetention_zero_time (r : ℝ) : dwellRetention r 0 = 1 := by
  simp [dwellRetention, trackingErrorFraction]

/-- Therefore the zero-duration periodic fixed point equals the state average. -/
theorem zero_duration_cycleFixed (r μ₀ μ₁ : ℝ) :
    cycleFixed (dwellRetention r 0) μ₀ μ₁ = (μ₀ + μ₁) / 2 := by
  rw [dwellRetention_zero_time]
  exact cycleFixed_one μ₀ μ₁




/-- Away from the removable `a = 1` singularity of the generic affine formula,
the two-state closed form is exactly the generic periodic-history fixed point. -/
theorem cycleFixed_eq_periodicFixed
    (a μ₀ μ₁ : ℝ) (ha : a ≠ 1) (hplus : 1 + a ≠ 0) :
    cycleFixed a μ₀ μ₁ = periodicFixed [(a, μ₀), (a, μ₁)] := by
  have hminus : 1 - a ≠ 0 := sub_ne_zero.mpr (Ne.symm ha)
  have hquad : 1 - a * a ≠ 0 := by
    rw [show 1 - a * a = (1 - a) * (1 + a) by ring]
    exact mul_ne_zero hminus hplus
  unfold periodicFixed historyOffset historyGain cycleFixed
  simp [run, step]
  have hquad' : 1 - a ^ 2 ≠ 0 := by simpa [pow_two] using hquad
  field_simp [hquad, hquad', hplus]
  ring

/-!
## Generator-level fast-switching duality

The stationary slow/fast theorem is symmetric in a useful way.  If the switching
operator itself is the fast operator and `Pslow` projects onto its equilibria,
then a generator normalized as

    Qswitch + delta * Qread

has the exact defect

    pi - Pslow pi = -delta * Rswitch (Qread pi).

Thus `delta` is the inverse switching-speed scale.  This is the algebraic
fast-switching/averaging theorem: when the switching corrector remains bounded,
the stationary law approaches the slow-driver equilibrium manifold as
`delta -> 0`.  No new singular-perturbation machinery is needed; it is the same
Poisson-corrector theorem with the biological roles exchanged.
-/

/-- Exact stationary averaging defect when switching is chosen as the fast
operator. -/
theorem stationary_averaging_defect
    {E : Type*} [AddCommGroup E] [Module ℝ E]
    (Qswitch Qread Pslow Rswitch : E →ₗ[ℝ] E)
    (delta : ℝ) (pi : E)
    (hRQ : Rswitch.comp Qswitch = LinearMap.id - Pslow)
    (hstationary : (Qswitch + delta • Qread) pi = 0) :
    pi - Pslow pi = -delta • Rswitch (Qread pi) := by
  exact StationaryMixture.defect_identity
    Qswitch Qread Pslow Rswitch delta pi hRQ hstationary

/-- Same theorem written in the more intuitive physical scaling
`Qread + delta⁻¹ Qswitch`.  Multiplying a stationary equation by a nonzero
`delta` does not change its stationary laws. -/
theorem stationary_averaging_defect_of_fast_generator
    {E : Type*} [AddCommGroup E] [Module ℝ E]
    (Qswitch Qread Pslow Rswitch : E →ₗ[ℝ] E)
    (delta : ℝ) (pi : E)
    (hdelta : delta ≠ 0)
    (hRQ : Rswitch.comp Qswitch = LinearMap.id - Pslow)
    (hstationary : (Qread + delta⁻¹ • Qswitch) pi = 0) :
    pi - Pslow pi = -delta • Rswitch (Qread pi) := by
  have hscaled := congrArg (fun z : E => delta • z) hstationary
  have hnormalized : (Qswitch + delta • Qread) pi = 0 := by
    simpa [LinearMap.add_apply, LinearMap.smul_apply, smul_add, smul_smul,
      hdelta, add_comm] using hscaled
  exact stationary_averaging_defect
    Qswitch Qread Pslow Rswitch delta pi hRQ hnormalized

end FastSwitching
end Theory
end StochasticQuantization
